//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 11:32:37 PM EDT 
//


package com.alphasystem.tanzil;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for SuraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alphasystem.com/tanzil}aya" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuraType", propOrder = {
    "aya"
})
public class SuraType {

    @XmlElement(required = true)
    protected List<AyaType> aya;
    @XmlAttribute(required = true)
    protected Integer index;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the aya property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aya property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAya().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AyaType }
     * 
     * 
     */
    public List<AyaType> getAya() {
        if (aya == null) {
            aya = new ArrayList<AyaType>();
        }
        return this.aya;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public SuraType withAya(AyaType... values) {
        if (values!= null) {
            for (AyaType value: values) {
                getAya().add(value);
            }
        }
        return this;
    }

    public SuraType withAya(Collection<AyaType> values) {
        if (values!= null) {
            getAya().addAll(values);
        }
        return this;
    }

    public SuraType withIndex(Integer value) {
        setIndex(value);
        return this;
    }

    public SuraType withName(String value) {
        setName(value);
        return this;
    }

    /**
     * Sets the value of the aya property.
     * 
     * @param aya
     *     allowed object is
     *     {@link AyaType }
     *     
     */
    public void setAya(List<AyaType> aya) {
        this.aya = aya;
    }

}
