//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 11:32:37 PM EDT 
//


package com.alphasystem.tanzil.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for SuraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alphasystem.com/tanzil}aya" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="verseNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "sura")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChapterType", propOrder = {
    "verses"
})
public class Chapter {

    @XmlElement(name = "aya", required = true)
    protected List<Verse> verses;
    @XmlAttribute(name = "index", required = true)
    protected Integer chapterNumber;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the aya property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aya property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Verse }
     * 
     * 
     */
    public List<Verse> getVerses() {
        if (verses == null) {
            verses = new ArrayList<Verse>();
        }
        return this.verses;
    }

    /**
     * Gets the value of the verseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChapterNumber() {
        return chapterNumber;
    }

    /**
     * Sets the value of the verseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChapterNumber(Integer value) {
        this.chapterNumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public Chapter withVerses(Verse... values) {
        if (values!= null) {
            for (Verse value: values) {
                getVerses().add(value);
            }
        }
        return this;
    }

    public Chapter withVerses(Collection<Verse> values) {
        if (values!= null) {
            getVerses().addAll(values);
        }
        return this;
    }

    public Chapter withChapterNumber(Integer value) {
        setChapterNumber(value);
        return this;
    }

    public Chapter withName(String value) {
        setName(value);
        return this;
    }

    /**
     * Sets the value of the aya property.
     * 
     * @param verses
     *     allowed object is
     *     {@link Verse }
     *     
     */
    public void setAya(List<Verse> verses) {
        this.verses = verses;
    }

}
