//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 11:32:37 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(elementFormDefault = UNQUALIFIED, attributeFormDefault = UNQUALIFIED)
package com.alphasystem.tanzil.model;

import javax.xml.bind.annotation.XmlNsForm;

import static javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED;